import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick3D
import QtQuick.Dialogs
ApplicationWindow {
  id: window; width: 1360; height: 860; visible: true; title: "Prometheus — CAD Workspace"; color: "#171b20"
  property color panel: "#20262c"; property color line: "#35404a"; property color text: "#dfe7ed"; property color muted: "#91a0ab"; property int selectedIndex: -1
  property bool xrayMode:false;property bool boundsMode:false;property var measurement:({})
  property bool perspectiveMode:true;property real panX:0;property real panY:0;property real orthoZoom:1
  property string transformMode:"move";property string transformFrame:"world";property real moveIncrement:0.005;property real rotateIncrement:5;property bool snapEnabled:true
  property real orbitX: -24; property real orbitY: -38; property real cameraDistance: Math.max(0.25, cadController.sceneDiameter * 2.0)
  property bool reviewChoicesValid:false
  function fitView() { orbitX=-24; orbitY=-38;panX=0;panY=0;orthoZoom=1;cameraDistance=Math.max(0.05,cadController.sceneDiameter*2.0) }
  function setView(x,y,orthographic) { orbitX=x;orbitY=y;panX=0;panY=0;orthoZoom=1;cameraDistance=Math.max(0.05,cadController.sceneDiameter*2.0);if(orthographic!==undefined)perspectiveMode=!orthographic }
  function nudgeSelection(axis,direction) { if(selectedIndex<0||cadController.geometryBusy)return;const p=cadController.parts[selectedIndex];let x=p.translationX,y=p.translationY,z=p.translationZ,rx=p.rotationX,ry=p.rotationY,rz=p.rotationZ;if(transformMode==="move"){const v=transformFrame==="local"?cadController.localAxisDirection(selectedIndex,axis):({x:axis==="X"?1:0,y:axis==="Y"?1:0,z:axis==="Z"?1:0});x+=direction*moveIncrement*v.x;y+=direction*moveIncrement*v.y;z+=direction*moveIncrement*v.z}else if(transformFrame==="local"){const r=cadController.composeLocalRotation(rx,ry,rz,axis,direction*rotateIncrement);rx=r.rx;ry=r.ry;rz=r.rz}else{if(axis==="X")rx+=direction*rotateIncrement;if(axis==="Y")ry+=direction*rotateIncrement;if(axis==="Z")rz+=direction*rotateIncrement}cadController.setPartPlacement(selectedIndex,x,y,z,rx,ry,rz) }
  function snapped(value,step){return Math.round(value/step)*step}
  function renderEngineeringValue(parameter){const claim=parameter.selected_claim||{};const value=claim.value||{};const unit=claim.unit||"";if(value.kind==="scalar")return String(value.value)+" "+unit;if(value.kind==="range")return String(value.minimum)+"–"+String(value.maximum)+" "+unit;if(value.kind==="enumeration")return (value.values||[]).join(", ");if(value.kind==="curve")return (value.points||[]).length+" points by "+value.independent_quantity+" ("+value.independent_unit+")";if(value.kind==="unknown")return "Unknown: "+value.reason;return "Unsupported value"}
  function resetReviewChoices(){reviewChoices.clear();for(let i=0;i<serviceController.parameters.length;i++){const claim=serviceController.parameters[i].selected_claim||{};reviewChoices.append({claim_id:claim.claim_id||"",status:"",note:""})}validateReviewChoices()}
  function validateReviewChoices(){let valid=reviewerField.text.trim()!==""&&reviewChoices.count===serviceController.parameters.length&&reviewChoices.count>0;for(let i=0;i<reviewChoices.count;i++){const row=reviewChoices.get(i);if(row.claim_id===""||row.status===""||row.note.trim()===""){valid=false;break}}reviewChoicesValid=valid}
  function reviewDecisionPayload(){const result=[];for(let i=0;i<reviewChoices.count;i++){const row=reviewChoices.get(i);result.push({claim_id:row.claim_id,status:row.status,note:row.note})}return result}
  Component.onCompleted:{if(startupStepPath!=="")cadController.importStepAsync(startupStepPath);if(demoCadInspect){boundsMode=true;perspectiveMode=false;selectedIndex=1}if(demoPlacement){boundsMode=true;selectedIndex=2;cadController.setPartPlacement(2,0,0.08,0,0,0,30)}if(demoEngineering){engineeringController.defineRevoluteJoint(1,2,"Z",0,90,cadController.parts[1].centerX,cadController.parts[1].centerY,cadController.parts[1].centerZ);engineeringController.defineMotorArmScenario(8,0.20,90,1.2,4,10,35);cadController.runJointSweepAsync(2,1,engineeringController.joint.pivot_x,engineeringController.joint.pivot_y,engineeringController.joint.pivot_z,"Z",0,90)}}
  header: Column { width: parent.width
    Rectangle { width: parent.width; height: 29; color: "#171b20"; Row { anchors.verticalCenter: parent.verticalCenter; leftPadding: 14; spacing: 24; Repeater { model: ["File","Edit","View","Assembly","Components","Test","Tools","Help"]; Label { text: modelData; color: window.text; font.pixelSize: 12 } } } }
    Rectangle { width: parent.width; height: 52; color: "#242b31"; border.color: line
      RowLayout { anchors.fill: parent; anchors.margins: 7; spacing: 7
        Label { text: "P"; color: "white"; font.bold: true; font.pixelSize: 20; horizontalAlignment: Text.AlignHCenter; verticalAlignment: Text.AlignVCenter; background: Rectangle{color:"#d7643d"} Layout.preferredWidth: 34; Layout.fillHeight: true }
        Label { text: "PROMETHEUS"; color: window.text; font.bold: true; Layout.rightMargin: 18 }
        Button { text: "Import STEP"; onClicked: stepDialog.open(); enabled:!cadController.busy }
        Button { text: "Open Project"; onClicked:openDialog.open(); enabled:!cadController.busy }
        Button { text: "Save Project"; onClicked:{cadController.setEngineeringState(engineeringController.projectState);saveDialog.open()} enabled:cadController.parts.length>0&&!cadController.busy }
        Button { text: "Add Component"; enabled: selectedIndex >= 0;onClicked:{serviceController.reset();componentDialog.open()} }
        Button { text:"Transform";enabled:selectedIndex>=0&&!cadController.geometryBusy;onClicked:{const p=cadController.parts[selectedIndex];moveX.text=String(p.translationX);moveY.text=String(p.translationY);moveZ.text=String(p.translationZ);rotateX.text=String(p.rotationX);rotateY.text=String(p.rotationY);rotateZ.text=String(p.rotationZ);moveDialog.open()} }
        Button{text:transformMode==="move"?"Move [W]":"Rotate [E]";enabled:selectedIndex>=0;onClicked:transformMode=transformMode==="move"?"rotate":"move";ToolTip.visible:hovered;ToolTip.text:"Toggle the viewport axis manipulator"}
        Button{text:transformFrame==="world"?"World":"Local";enabled:selectedIndex>=0;onClicked:transformFrame=transformFrame==="world"?"local":"world";ToolTip.visible:hovered;ToolTip.text:"Toggle world/local transform coordinates"}
        Button{text:snapEnabled?"Snap ✓":"Snap";checkable:true;checked:snapEnabled;onClicked:snapEnabled=checked;ToolTip.visible:hovered;ToolTip.text:"Grid/angular snap; hold Alt while dragging to bypass"}
        Button{text:"↶";enabled:cadController.canUndo&&!cadController.geometryBusy;ToolTip.visible:hovered;ToolTip.text:"Undo placement (Ctrl+Z)";onClicked:cadController.undoPlacement()}Button{text:"↷";enabled:cadController.canRedo&&!cadController.geometryBusy;ToolTip.visible:hovered;ToolTip.text:"Redo placement (Ctrl+Y)";onClicked:cadController.redoPlacement()}
        Button { text: "Measure";enabled:cadController.parts.length>1;onClicked:measureDialog.open() }
        Button { text:"Snap Mate";enabled:cadController.parts.length>1&&!cadController.geometryBusy;onClicked:mateDialog.open() }
        Button { text: xrayMode?"X-Ray ✓":"X-Ray";checkable:true;checked:xrayMode;onClicked:xrayMode=checked }
        Button { text: boundsMode?"Bounds ✓":"Bounds";checkable:true;checked:boundsMode;onClicked:boundsMode=checked }
        Button { text: "Overlaps";enabled:cadController.interferences.length>0;onClicked:connectionDialog.open() }
        Button { text:"Connections"+(cadController.connections.length>0?" ("+cadController.connections.length+")":"");enabled:cadController.connections.length>0;onClicked:semanticConnectionsDialog.open() }
        Button { text: engineeringController.jointConfigured?"Joint ✓":"Define Joint"; enabled: cadController.parts.length>1;onClicked:jointDialog.open() }
        Button { text: engineeringController.scenarioConfigured?"Scenario ✓":"Add Scenario";onClicked:scenarioDialog.open() }
        Item { Layout.fillWidth: true }
        Button { text: cadController.sweepBusy?"Checking…":"Test Build"; highlighted: true;enabled:engineeringController.jointConfigured&&engineeringController.scenarioConfigured&&!cadController.sweepBusy&&!cadController.geometryBusy;ToolTip.visible:hovered;ToolTip.text:"Conformance demo: the current C++ motor-arm checks still use fixed fixture inputs and do not yet consume this published package.";onClicked:{const source=cadController.parts[engineeringController.joint.source_index];cadController.runJointSweepAsync(engineeringController.joint.target_index,engineeringController.joint.source_index,engineeringController.joint.pivot_x+source.translationX,engineeringController.joint.pivot_y+source.translationY,engineeringController.joint.pivot_z+source.translationZ,engineeringController.joint.axis,engineeringController.joint.minimum_deg,engineeringController.joint.maximum_deg)} }
      }
    }
  }
  RowLayout { anchors.fill: parent; spacing: 1
    Rectangle { Layout.minimumWidth: 245; Layout.maximumWidth:245; Layout.fillHeight: true; color: panel
      ColumnLayout { anchors.fill: parent; spacing: 0
        Label { text: "ASSEMBLY"; color: muted; font.bold: true; font.pixelSize: 11; Layout.margins: 13 }
        Label { visible: cadController.parts.length===0; text: "Import a STEP assembly to begin."; color: muted; wrapMode: Text.WordWrap; Layout.margins: 14; Layout.fillWidth: true }
        ListView { Layout.fillWidth:true; Layout.fillHeight:true; model:cadController.parts; clip:true
          delegate: Rectangle { width:ListView.view.width; height:48; color:index===selectedIndex?"#2e424f":"transparent"; border.color:index===selectedIndex?"#3d9bd6":"transparent"
            Column { anchors.verticalCenter:parent.verticalCenter; x:14; spacing:2; Label{text:"◇  "+modelData.name;color:window.text} Label{text:modelData.componentLabel!==""?modelData.componentLabel:modelData.persistentId;color:modelData.componentLabel!==""?"#70c99a":muted;font.pixelSize:10} }
            Button{anchors.right:parent.right;anchors.verticalCenter:parent.verticalCenter;anchors.rightMargin:7;text:modelData.visible?"●":"○";flat:true;onClicked:cadController.toggleVisible(index)}
            MouseArea{anchors.left:parent.left;anchors.right:parent.right;anchors.rightMargin:42;anchors.top:parent.top;anchors.bottom:parent.bottom;onClicked:selectedIndex=index;onDoubleClicked:cadController.isolate(index)}
          }
        }
      }
    }
    Rectangle { Layout.fillWidth:true; Layout.fillHeight:true; color:"#151a1f"
      View3D { id:view;anchors.fill:parent;camera:perspectiveMode?perspectiveCamera:orthographicCamera
        environment: SceneEnvironment { clearColor:"#111820"; backgroundMode:SceneEnvironment.Color; antialiasingMode:SceneEnvironment.MSAA; antialiasingQuality:SceneEnvironment.VeryHigh; tonemapMode:SceneEnvironment.TonemapModeFilmic }
        Node { id:cameraRig;position:Qt.vector3d(panX,panY,0);eulerRotation.x:orbitX;eulerRotation.y:orbitY;PerspectiveCamera{id:perspectiveCamera;z:cameraDistance;clipNear:Math.max(0.00001,cadController.sceneDiameter*0.0001);clipFar:100}OrthographicCamera{id:orthographicCamera;z:cameraDistance;clipNear:0.00001;clipFar:100;horizontalMagnification:orthoZoom*Math.min(view.width,view.height)/(Math.max(cadController.sceneDiameter,0.01)*1.65);verticalMagnification:horizontalMagnification} }
        DirectionalLight { eulerRotation.x:-38; eulerRotation.y:-32; brightness:1.35;castsShadow:true;shadowFactor:45;shadowMapQuality:Light.ShadowMapQualityHigh }
        DirectionalLight { eulerRotation.x:35;eulerRotation.y:145;brightness:0.45;color:"#9fc8e7" }
        Node { id:assemblyRoot;eulerRotation.x:-90; position:Qt.vector3d(-cadController.centerX,-cadController.centerY,-cadController.centerZ)
          Node{id:gridRoot;position:Qt.vector3d(cadController.centerX,cadController.centerY,cadController.sceneMinZ-Math.max(cadController.sceneDiameter*0.002,0.001));property real spacing:cadController.sceneDiameter/10;property real extent:cadController.sceneDiameter*1.35;property real thickness:Math.max(cadController.sceneDiameter*0.0012,0.00035)
            Repeater3D{model:21;Model{source:"#Cube";position:Qt.vector3d((index-10)*gridRoot.spacing,0,0);scale:Qt.vector3d(gridRoot.thickness/100,gridRoot.extent/100,gridRoot.thickness/100);materials:[PrincipledMaterial{baseColor:index===10?"#526878":"#26343e";lighting:PrincipledMaterial.NoLighting}]}}
            Repeater3D{model:21;Model{source:"#Cube";position:Qt.vector3d(0,(index-10)*gridRoot.spacing,0);scale:Qt.vector3d(gridRoot.extent/100,gridRoot.thickness/100,gridRoot.thickness/100);materials:[PrincipledMaterial{baseColor:index===10?"#526878":"#26343e";lighting:PrincipledMaterial.NoLighting}]}}
          }
          Repeater3D{model:cadController.parts;Node{position:Qt.vector3d(modelData.centerX+modelData.translationX,modelData.centerY+modelData.translationY,modelData.centerZ+modelData.translationZ);eulerRotation.z:modelData.rotationZ;Node{eulerRotation.y:modelData.rotationY;Node{eulerRotation.x:modelData.rotationX;Model{property int partIndex:index;position:Qt.vector3d(-modelData.centerX,-modelData.centerY,-modelData.centerZ);geometry:modelData.geometry;visible:modelData.visible;opacity:xrayMode?0.28:1;pickable:true;castsShadows:!xrayMode;receivesShadows:true;materials:[PrincipledMaterial{baseColor:index===selectedIndex?"#36a5e3":"#8b9dab";roughness:0.46;metalness:0.08;lighting:PrincipledMaterial.FragmentLighting}]}}}}}
          Repeater3D{model:cadController.parts;Node{visible:boundsMode&&modelData.visible;position:Qt.vector3d(modelData.centerX+modelData.translationX,modelData.centerY+modelData.translationY,modelData.centerZ+modelData.translationZ);eulerRotation.z:modelData.rotationZ;Node{eulerRotation.y:modelData.rotationY;Node{eulerRotation.x:modelData.rotationX;Model{source:"#Cube";scale:Qt.vector3d(Math.max(modelData.sizeX,0.0001)/100,Math.max(modelData.sizeY,0.0001)/100,Math.max(modelData.sizeZ,0.0001)/100);opacity:0.18;materials:[PrincipledMaterial{baseColor:index===selectedIndex?"#32b3ff":"#d7a94a";lighting:PrincipledMaterial.NoLighting}]}}}}}
          Model{visible:engineeringController.jointConfigured&&cadController.parts.length>engineeringController.joint.target_index;source:"#Cylinder";position:engineeringController.jointConfigured?Qt.vector3d(engineeringController.joint.pivot_x+cadController.parts[engineeringController.joint.source_index].translationX,engineeringController.joint.pivot_y+cadController.parts[engineeringController.joint.source_index].translationY,engineeringController.joint.pivot_z+cadController.parts[engineeringController.joint.source_index].translationZ):Qt.vector3d(0,0,0);scale:Qt.vector3d(0.00005,Math.max(cadController.sceneDiameter,0.1)/100,0.00005);eulerRotation.x:engineeringController.joint.axis==="Z"?90:0;eulerRotation.z:engineeringController.joint.axis==="X"?90:0;materials:[PrincipledMaterial{baseColor:"#45b7e8";lighting:PrincipledMaterial.NoLighting}]}
          Node{id:transformGizmo;visible:selectedIndex>=0&&selectedIndex<cadController.parts.length&&!cadController.geometryBusy;property real span:Math.max(cadController.sceneDiameter*0.18,0.035);position:selectedIndex>=0?Qt.vector3d(cadController.parts[selectedIndex].centerX+cadController.parts[selectedIndex].translationX,cadController.parts[selectedIndex].centerY+cadController.parts[selectedIndex].translationY,cadController.parts[selectedIndex].centerZ+cadController.parts[selectedIndex].translationZ):Qt.vector3d(0,0,0)
            Node{eulerRotation.z:transformFrame==="local"&&selectedIndex>=0?cadController.parts[selectedIndex].rotationZ:0;Node{eulerRotation.y:transformFrame==="local"&&selectedIndex>=0?cadController.parts[selectedIndex].rotationY:0;Node{id:gizmoAxes;eulerRotation.x:transformFrame==="local"&&selectedIndex>=0?cadController.parts[selectedIndex].rotationX:0
            Model{property string gizmoAxis:"X";source:"#Cylinder";position:Qt.vector3d(transformGizmo.span/2,0,0);eulerRotation.z:90;scale:Qt.vector3d(0.000045,transformGizmo.span/100,0.000045);pickable:true;materials:[PrincipledMaterial{baseColor:"#ef655e";lighting:PrincipledMaterial.NoLighting}]}
            Model{property string gizmoAxis:"Y";source:"#Cylinder";position:Qt.vector3d(0,transformGizmo.span/2,0);scale:Qt.vector3d(0.000045,transformGizmo.span/100,0.000045);pickable:true;materials:[PrincipledMaterial{baseColor:"#65cf87";lighting:PrincipledMaterial.NoLighting}]}
            Model{property string gizmoAxis:"Z";source:"#Cylinder";position:Qt.vector3d(0,0,transformGizmo.span/2);eulerRotation.x:90;scale:Qt.vector3d(0.000045,transformGizmo.span/100,0.000045);pickable:true;materials:[PrincipledMaterial{baseColor:"#55a8ec";lighting:PrincipledMaterial.NoLighting}]}
            Model{property string gizmoAxis:"X";source:"#Sphere";position:Qt.vector3d(transformGizmo.span,0,0);scale:Qt.vector3d(0.00012,0.00012,0.00012);pickable:true;materials:[PrincipledMaterial{baseColor:"#ef655e";lighting:PrincipledMaterial.NoLighting}]}
            Model{property string gizmoAxis:"Y";source:"#Sphere";position:Qt.vector3d(0,transformGizmo.span,0);scale:Qt.vector3d(0.00012,0.00012,0.00012);pickable:true;materials:[PrincipledMaterial{baseColor:"#65cf87";lighting:PrincipledMaterial.NoLighting}]}
            Model{property string gizmoAxis:"Z";source:"#Sphere";position:Qt.vector3d(0,0,transformGizmo.span);scale:Qt.vector3d(0.00012,0.00012,0.00012);pickable:true;materials:[PrincipledMaterial{baseColor:"#55a8ec";lighting:PrincipledMaterial.NoLighting}]}
            }}}
          }
        }
      }
      MouseArea { id:viewInput;anchors.fill:parent;acceptedButtons:Qt.LeftButton|Qt.MiddleButton|Qt.RightButton;property real lastX;property real lastY;property real pressX;property real pressY;property real cursorX;property real cursorY;property string draggingAxis:"";property bool dragged:false;property bool suppressClick:false;property var dragStart:({});property string transientValue:""
        function projectedFraction(axis,dx,dy){const origin=view.mapFrom3DScene(gizmoAxes.mapPositionToScene(Qt.vector3d(0,0,0)));let local=axis==="X"?Qt.vector3d(transformGizmo.span,0,0):axis==="Y"?Qt.vector3d(0,transformGizmo.span,0):Qt.vector3d(0,0,transformGizmo.span);const endpoint=view.mapFrom3DScene(gizmoAxes.mapPositionToScene(local));const vx=endpoint.x-origin.x,vy=endpoint.y-origin.y;const length2=vx*vx+vy*vy;return length2<16?0:(dx*vx+dy*vy)/length2}
        onPressed:function(mouse){lastX=mouse.x;lastY=mouse.y;if(mouse.button===Qt.LeftButton){const hit=view.pick(mouse.x,mouse.y);if(hit.objectHit&&hit.objectHit.gizmoAxis!==undefined&&cadController.beginPlacementPreview(selectedIndex)){draggingAxis=hit.objectHit.gizmoAxis;pressX=mouse.x;pressY=mouse.y;dragged=false;const p=cadController.parts[selectedIndex];const v=transformFrame==="local"?cadController.localAxisDirection(selectedIndex,draggingAxis):({x:draggingAxis==="X"?1:0,y:draggingAxis==="Y"?1:0,z:draggingAxis==="Z"?1:0});dragStart={x:p.translationX,y:p.translationY,z:p.translationZ,rx:p.rotationX,ry:p.rotationY,rz:p.rotationZ,dx:v.x,dy:v.y,dz:v.z}}}}
        onPositionChanged:function(mouse){cursorX=mouse.x;cursorY=mouse.y;if(draggingAxis!==""&&(mouse.buttons&Qt.LeftButton)){const dx=mouse.x-pressX,dy=mouse.y-pressY;if(Math.abs(dx)+Math.abs(dy)>3)dragged=true;if(!dragged)return;const fraction=projectedFraction(draggingAxis,dx,dy);const useSnap=snapEnabled&&!(mouse.modifiers&Qt.AltModifier);let x=dragStart.x,y=dragStart.y,z=dragStart.z,rx=dragStart.rx,ry=dragStart.ry,rz=dragStart.rz;if(transformMode==="move"){let delta=fraction*transformGizmo.span;if(useSnap)delta=snapped(delta,moveIncrement);x+=delta*dragStart.dx;y+=delta*dragStart.dy;z+=delta*dragStart.dz;transientValue=draggingAxis+"  "+(delta*1000).toFixed(useSnap?0:2)+" mm"}else{let delta=fraction*90;if(useSnap)delta=snapped(delta,rotateIncrement);if(transformFrame==="local"){const r=cadController.composeLocalRotation(dragStart.rx,dragStart.ry,dragStart.rz,draggingAxis,delta);rx=r.rx;ry=r.ry;rz=r.rz}else{if(draggingAxis==="X")rx+=delta;if(draggingAxis==="Y")ry+=delta;if(draggingAxis==="Z")rz+=delta}transientValue=draggingAxis+"  "+delta.toFixed(useSnap?0:2)+"°"}cadController.previewPartPlacement(selectedIndex,x,y,z,rx,ry,rz);return}if((mouse.buttons&Qt.RightButton)||((mouse.buttons&Qt.MiddleButton)&&(mouse.modifiers&Qt.ShiftModifier))){const dx=mouse.x-lastX,dy=mouse.y-lastY;panX+=dx*cameraDistance*0.0015;panY-=dy*cameraDistance*0.0015;lastX=mouse.x;lastY=mouse.y;return}if(mouse.buttons&Qt.MiddleButton){const dx=mouse.x-lastX,dy=mouse.y-lastY;orbitY+=dx*0.35;orbitX=Math.max(-89,Math.min(89,orbitX+dy*0.35));lastX=mouse.x;lastY=mouse.y}}
        onReleased:function(mouse){if(mouse.button===Qt.LeftButton&&draggingAxis!==""){if(dragged)cadController.commitPlacementPreview();else cadController.cancelPlacementPreview();draggingAxis="";transientValue=""}}
        onCanceled:{if(draggingAxis!=="")cadController.cancelPlacementPreview();draggingAxis="";dragged=false;transientValue=""}
        onWheel:function(wheel){if(perspectiveMode)cameraDistance=Math.max(cadController.sceneDiameter*0.06,Math.min(cadController.sceneDiameter*20,cameraDistance*(wheel.angleDelta.y>0?0.82:1.20)));else orthoZoom=Math.max(0.15,Math.min(30,orthoZoom*(wheel.angleDelta.y>0?1.18:0.84)))}
        onClicked:function(mouse){if(suppressClick){suppressClick=false;return}if(dragged){dragged=false;return}const hit=view.pick(mouse.x,mouse.y);if(!hit.objectHit)return;if(hit.objectHit.gizmoAxis!==undefined){nudgeSelection(hit.objectHit.gizmoAxis,(mouse.modifiers&Qt.ShiftModifier)?-1:1);return}if(hit.objectHit.partIndex!==undefined)selectedIndex=hit.objectHit.partIndex}
      }
      Rectangle{visible:viewInput.draggingAxis!==""&&viewInput.dragged;x:Math.min(view.width-width-8,viewInput.cursorX+16);y:Math.min(view.height-height-8,viewInput.cursorY+16);width:145;height:34;radius:4;color:"#202830ee";border.color:viewInput.draggingAxis==="X"?"#ef655e":viewInput.draggingAxis==="Y"?"#65cf87":"#55a8ec";Label{anchors.centerIn:parent;text:viewInput.transientValue;color:window.text;font.bold:true}}
      Row{anchors.right:parent.right;anchors.top:parent.top;anchors.margins:12;spacing:5;Button{text:"ISO";onClicked:setView(-24,-38,false)}Button{text:"TOP";onClicked:setView(-89,0,true)}Button{text:"FRONT";onClicked:setView(0,0,true)}Button{text:perspectiveMode?"PERSP":"ORTHO";onClicked:perspectiveMode=!perspectiveMode}Button{text:"Show all";onClicked:cadController.showAll()}Button { text:"Fit";onClicked:fitView() }}
      Rectangle{anchors.right:parent.right;anchors.top:parent.top;anchors.rightMargin:14;anchors.topMargin:52;width:66;height:66;color:"#26313a";border.color:"#60727f";radius:4;Column{anchors.centerIn:parent;spacing:2;Label{text:Math.abs(orbitX)>80?"TOP":Math.abs(orbitY)<5?"FRONT":"ISO";color:"#a9d5ee";font.bold:true;anchors.horizontalCenter:parent.horizontalCenter}Label{text:perspectiveMode?"Perspective":"Orthographic";color:muted;font.pixelSize:8;anchors.horizontalCenter:parent.horizontalCenter}}MouseArea{anchors.fill:parent;onClicked:setView(-24,-38)}}
      Rectangle { anchors.left:parent.left;anchors.bottom:parent.bottom;anchors.margins:12;width:750;height:28;color:"#252c32cc";border.color:line;Label{anchors.centerIn:parent;text:"Middle: orbit  •  Right drag or Shift+Middle: pan  •  Wheel: zoom  •  W/E: move/rotate  •  F: fit";color:muted;font.pixelSize:11} }
      Column { anchors.centerIn:parent;visible:cadController.parts.length===0;spacing:8;Label{text:"No assembly loaded";color:window.text;font.pixelSize:25}Label{text:"Import a real STEP file to inspect its tessellation.";color:muted} }
    }
    Rectangle { Layout.minimumWidth:285; Layout.maximumWidth:285; Layout.fillHeight:true; color:panel
      Column { anchors.fill:parent;anchors.margins:14;spacing:10
        Label{text:"PROPERTIES   •   EVIDENCE";color:muted;font.bold:true;font.pixelSize:11}
        Rectangle{width:parent.width;height:1;color:line}
        Label{text:selectedIndex>=0?cadController.parts[selectedIndex].name:"No selection";color:window.text;font.pixelSize:18}
        Rectangle{visible:selectedIndex>=0;width:parent.width;height:168;color:"#151b20";border.color:line;radius:3;clip:true
          View3D{anchors.fill:parent;anchors.margins:1;camera:detailCamera;environment:SceneEnvironment{clearColor:"#151b20";backgroundMode:SceneEnvironment.Color;antialiasingMode:SceneEnvironment.MSAA;antialiasingQuality:SceneEnvironment.High}
            PerspectiveCamera{id:detailCamera;z:selectedIndex>=0?Math.max(0.025,Math.max(cadController.parts[selectedIndex].sizeX,cadController.parts[selectedIndex].sizeY,cadController.parts[selectedIndex].sizeZ)*2.25):0.1;clipNear:0.00001;clipFar:10}
            DirectionalLight{eulerRotation.x:-35;eulerRotation.y:-35;brightness:1.5}DirectionalLight{eulerRotation.x:30;eulerRotation.y:140;brightness:0.5;color:"#a9d2ed"}
            Node{visible:selectedIndex>=0;eulerRotation.x:-90;eulerRotation.y:-28;Model{geometry:selectedIndex>=0?cadController.parts[selectedIndex].geometry:null;position:selectedIndex>=0?Qt.vector3d(-cadController.parts[selectedIndex].centerX,-cadController.parts[selectedIndex].centerY,-cadController.parts[selectedIndex].centerZ):Qt.vector3d(0,0,0);materials:[PrincipledMaterial{baseColor:"#73b8de";roughness:0.42;metalness:0.08}]}}
          }
          Label{anchors.left:parent.left;anchors.bottom:parent.bottom;anchors.margins:7;text:"ISOLATED SELECTION";color:muted;font.bold:true;font.pixelSize:9}
        }
        Label{text:selectedIndex>=0?(cadController.parts[selectedIndex].componentLabel!==""?cadController.parts[selectedIndex].componentLabel:"Geometry model"):"Select an assembly entity.";color:cadController.parts.length>0&&selectedIndex>=0&&cadController.parts[selectedIndex].componentLabel!==""?"#70c99a":muted}
        Label{visible:cadController.sourceName!=="";text:"Source\n"+cadController.sourceName;color:muted;topPadding:14}
        Label{visible:selectedIndex>=0;text:"IMPORTED B-REP";color:muted;font.bold:true;font.pixelSize:10;topPadding:8}
        Label{visible:selectedIndex>=0;text:"Bounds (m)\n"+cadController.parts[selectedIndex].sizeX.toFixed(4)+" × "+cadController.parts[selectedIndex].sizeY.toFixed(4)+" × "+cadController.parts[selectedIndex].sizeZ.toFixed(4)+"\nVolume  "+cadController.parts[selectedIndex].volumeM3.toExponential(3)+" m³\nSurface area  "+cadController.parts[selectedIndex].surfaceAreaM2.toExponential(3)+" m²\nTopology  "+cadController.parts[selectedIndex].faceCount+" faces  •  "+cadController.parts[selectedIndex].edgeCount+" edges";color:muted}
        Label{visible:selectedIndex>=0;text:"Material  unknown\nMass  unknown — not inferred from geometry";color:"#e0ac62";font.pixelSize:11;topPadding:5}
        Label{visible:selectedIndex>=0;text:"PLACEMENT OFFSET (m)\nX  "+cadController.parts[selectedIndex].translationX.toFixed(4)+"   Y  "+cadController.parts[selectedIndex].translationY.toFixed(4)+"   Z  "+cadController.parts[selectedIndex].translationZ.toFixed(4)+"\nROTATION XYZ (deg)\nX  "+cadController.parts[selectedIndex].rotationX.toFixed(2)+"   Y  "+cadController.parts[selectedIndex].rotationY.toFixed(2)+"   Z  "+cadController.parts[selectedIndex].rotationZ.toFixed(2);color:cadController.parts.length>0&&selectedIndex>=0&&(cadController.parts[selectedIndex].translationX!==0||cadController.parts[selectedIndex].translationY!==0||cadController.parts[selectedIndex].translationZ!==0||cadController.parts[selectedIndex].rotationX!==0||cadController.parts[selectedIndex].rotationY!==0||cadController.parts[selectedIndex].rotationZ!==0)?"#70c99a":muted;font.pixelSize:11;topPadding:5}
        Column{visible:selectedIndex>=0;width:parent.width;spacing:5;Label{text:(transformMode==="move"?"MOVE":"ROTATE")+" • "+transformFrame.toUpperCase()+" AXES";color:muted;font.bold:true;font.pixelSize:10}Row{spacing:5;Repeater{model:["X","Y","Z"];Button{required property string modelData;text:"−"+modelData;width:39;onClicked:nudgeSelection(modelData,-1)} }Repeater{model:["X","Y","Z"];Button{required property string modelData;text:"+"+modelData;width:39;onClicked:nudgeSelection(modelData,1)}}}Label{text:transformMode==="move"?"Step: "+(moveIncrement*1000).toFixed(0)+" mm":"Step: "+rotateIncrement.toFixed(0)+"°";color:muted;font.pixelSize:10}Row{spacing:5;Button{text:"Fine";flat:true;onClicked:{if(transformMode==="move")moveIncrement=0.001;else rotateIncrement=1}}Button{text:"Medium";flat:true;onClicked:{if(transformMode==="move")moveIncrement=0.005;else rotateIncrement=5}}Button{text:"Coarse";flat:true;onClicked:{if(transformMode==="move")moveIncrement=0.025;else rotateIncrement=15}}}}
        Label{visible:cadController.interferences.length>0;text:cadController.interferences.length+" confirmed static interference"+(cadController.interferences.length===1?"":"s");color:"#e87972";font.bold:true;topPadding:8}
        Label{visible:cadController.connections.length>0;text:cadController.connections.length+" user-confirmed semantic connection"+(cadController.connections.length===1?"":"s");color:"#70c99a";font.bold:true}
        Label{visible:cadController.error!=="";text:"Import failed\n"+cadController.error;color:"#e47a72";wrapMode:Text.WordWrap;width:parent.width}
      }
    }
  }
  footer: Rectangle { height:25;color:"#1a2025";border.color:line;RowLayout{anchors.fill:parent;anchors.leftMargin:10;anchors.rightMargin:10;Label{text:selectedIndex>=0?"Selected: "+cadController.parts[selectedIndex].name:"Selected: none";color:muted;font.pixelSize:11}Label{visible:cadController.warnings.length>0;text:"⚠ "+cadController.warnings.join(" • ");color:"#e0ac62";font.pixelSize:10}Item{Layout.fillWidth:true}Label{text:"Fixture service: "+(serviceController.online?"connected":"offline")+"   •   Units: SI   •   OCCT 7.9.3   •   "+(cadController.busy?"Importing…":"Ready");color:serviceController.online?"#74c89c":muted;font.pixelSize:11}} }
  FileDialog { id:stepDialog; title:"Import STEP assembly"; nameFilters:["STEP assemblies (*.step *.stp)"]; onAccepted:cadController.importStepAsync(selectedFile.toLocalFile()) }
  FileDialog { id:saveDialog;title:"Save Prometheus project";fileMode:FileDialog.SaveFile;nameFilters:["Prometheus project (*.prometheus)"];onAccepted:cadController.saveProject(selectedFile.toLocalFile()) }
  FileDialog { id:openDialog;title:"Open Prometheus project";fileMode:FileDialog.OpenFile;nameFilters:["Prometheus project (*.prometheus)"];onAccepted:cadController.openProject(selectedFile.toLocalFile()) }
  ListModel{id:reviewChoices}
  Shortcut{sequence:"F";onActivated:fitView()}Shortcut{sequence:"1";onActivated:setView(0,0,true)}Shortcut{sequence:"2";onActivated:setView(-89,0,true)}Shortcut{sequence:"3";onActivated:setView(-24,-38,false)}Shortcut{sequence:"H";onActivated:if(selectedIndex>=0)cadController.toggleVisible(selectedIndex)}Shortcut{sequence:"Shift+H";onActivated:cadController.showAll()}Shortcut{sequence:"5";onActivated:perspectiveMode=!perspectiveMode}
  Shortcut{sequence:"Ctrl+Z";onActivated:cadController.undoPlacement()}Shortcut{sequence:"Ctrl+Y";onActivated:cadController.redoPlacement()}
  Shortcut{sequence:"W";onActivated:transformMode="move"}Shortcut{sequence:"E";onActivated:transformMode="rotate"}
  Shortcut{sequence:"Shift+Left";onActivated:panX-=cameraDistance*0.03}Shortcut{sequence:"Shift+Right";onActivated:panX+=cameraDistance*0.03}Shortcut{sequence:"Shift+Up";onActivated:panY+=cameraDistance*0.03}Shortcut{sequence:"Shift+Down";onActivated:panY-=cameraDistance*0.03}
  Shortcut{sequence:"Escape";onActivated:{if(viewInput.draggingAxis!==""){cadController.cancelPlacementPreview();viewInput.draggingAxis="";viewInput.dragged=false;viewInput.suppressClick=true;viewInput.transientValue=""}}}
  Rectangle { anchors.fill:parent;color:"#11171dcc";visible:cadController.busy||cadController.sweepBusy||cadController.geometryBusy;z:100;Column{anchors.centerIn:parent;spacing:12;BusyIndicator{running:true;anchors.horizontalCenter:parent.horizontalCenter}Label{text:cadController.sweepBusy?"Sweeping joint range with Open Cascade…":cadController.geometryBusy?"Recomputing exact placement interference…":"Importing STEP assembly…";color:window.text}Button{visible:cadController.busy;text:"Cancel";onClicked:cadController.cancelImport();anchors.horizontalCenter:parent.horizontalCenter}} }
  Connections { target:cadController;function onImportFinished(success){if(success)setView(-24,-38,false)} function onEngineeringStateChanged(){if(Object.keys(cadController.engineeringState).length>0)engineeringController.restore(cadController.engineeringState)} }
  Connections { target:cadController;function onSweepFinished(){engineeringController.runChecks(cadController.interferences,cadController.sweepResults,true);resultsDialog.open()} }
  property string reviewStateToken:""
  Connections { target:serviceController;function onChanged(){const candidateId=serviceController.candidate.id;if(candidateId===undefined){reviewStateToken="";reviewChoices.clear();reviewerField.text="";validateReviewChoices();return}const nextToken=String(candidateId)+":"+String(serviceController.draftVersion);if(nextToken!==reviewStateToken){reviewStateToken=nextToken;reviewerField.text="";resetReviewChoices()}if(demoResearch){selectedIndex=Math.min(1,cadController.parts.length-1);componentDialog.open()}} }
  Popup { id:componentDialog;anchors.centerIn:Overlay.overlay;width:1040;height:780;modal:true;focus:true;closePolicy:Popup.CloseOnEscape;background:Rectangle{color:"#222a31";border.color:"#53616c";radius:3}
    ColumnLayout{anchors.fill:parent;anchors.margins:20;spacing:12
      RowLayout{Layout.fillWidth:true;Column{Label{text:"ADD COMPONENT";color:muted;font.bold:true;font.pixelSize:11}Label{text:serviceController.publicationIntegrity==="sealed_v2"?"Reviewed input published":"Review conformance fixture";color:window.text;font.pixelSize:23}}Item{Layout.fillWidth:true}Button{text:"×";flat:true;onClicked:componentDialog.close()}}
      Rectangle{Layout.fillWidth:true;height:1;color:line}
      RowLayout{Layout.fillWidth:true;visible:serviceController.candidate.id===undefined
        ColumnLayout{Layout.fillWidth:true;Label{text:"FIXED PROGRAM 01B COMPONENT CATALOG";color:muted;font.bold:true;font.pixelSize:10}ComboBox{id:fixtureChoice;Layout.fillWidth:true;model:serviceController.fixtureChoices;textRole:"label";valueRole:"fixture_id"}Label{text:"Only the three exact local catalog identities are accepted; no source URL or free-form identity is transmitted.";color:muted;wrapMode:Text.WordWrap;Layout.fillWidth:true}}
        Button{text:"Load fixture";enabled:!serviceController.busy&&fixtureChoice.currentIndex>=0;onClicked:serviceController.loadFixture(fixtureChoice.currentValue);Layout.alignment:Qt.AlignBottom}
      }
      ColumnLayout{Layout.fillWidth:true;visible:serviceController.busy;BusyIndicator{running:true;Layout.alignment:Qt.AlignHCenter}Label{text:serviceController.status==="acquiring_exact_package"?"Acquiring and independently verifying the exact published bytes…":"Loading the selected fixed fixture and compiling its selected claims…";color:muted;Layout.alignment:Qt.AlignHCenter}}
      Label{visible:serviceController.error!=="";text:serviceController.error+(serviceController.errorCode!==""?" ["+serviceController.errorCode+"]":"");color:"#e87972";wrapMode:Text.WordWrap;Layout.fillWidth:true}
      RowLayout{Layout.fillWidth:true;visible:serviceController.candidate.id!==undefined
        Column{Label{text:(serviceController.candidate.manufacturer||"")+"  "+(serviceController.candidate.part_number||"");color:window.text;font.pixelSize:19}Label{text:"Revision "+(serviceController.candidate.revision||"")+"  •  draft version "+serviceController.draftVersion;color:muted}}
        Item{Layout.fillWidth:true}Column{Label{text:"Publication: "+(serviceController.publicationIntegrity==="sealed_v2"?"published":"draft");color:serviceController.publicationIntegrity==="sealed_v2"?"#83b6d5":"#e0ac62";font.bold:true}Label{text:"Execution readiness: "+(serviceController.executionReadiness===""?"not evaluated":serviceController.executionReadiness);color:serviceController.executionReadiness==="ready"?"#70c99a":serviceController.executionReadiness==="blocked"?"#e0ac62":muted;font.bold:true}}
      }
      Label{visible:serviceController.parameters.length>0;text:"REVIEW EACH SELECTED CLAIM AND ITS PROVENANCE";color:muted;font.bold:true;font.pixelSize:11}
      ListView{Layout.fillWidth:true;Layout.fillHeight:true;clip:true;model:serviceController.parameters;spacing:3
        delegate:Rectangle{width:ListView.view.width;height:120;color:index%2?"#1e252b":"#1b2228";border.color:"#303b44"
          RowLayout{anchors.fill:parent;anchors.margins:9;spacing:10
            ColumnLayout{Layout.preferredWidth:210;Label{text:String(modelData.name).replace(/_/g," ");color:window.text;font.bold:true}Label{text:renderEngineeringValue(modelData);color:"#9fd1eb";wrapMode:Text.WordWrap;Layout.fillWidth:true}Label{text:String((modelData.selected_claim||{}).provenance||"").replace(/_/g," ");color:"#77c49b";font.pixelSize:10}}
            ColumnLayout{Layout.fillWidth:true;Label{text:"Claim "+String((modelData.selected_claim||{}).claim_id||"");color:muted;font.pixelSize:10;elide:Text.ElideMiddle;Layout.fillWidth:true}Label{text:"Fingerprint "+String((modelData.selected_claim||{}).claim_fingerprint||"");color:"#83b6d5";font.pixelSize:10;elide:Text.ElideMiddle;Layout.fillWidth:true}Label{text:"Evidence records: "+((modelData.selected_claim||{}).evidence_ids||[]).length;color:muted;font.pixelSize:10}}
            ColumnLayout{Layout.preferredWidth:210;ComboBox{id:decisionChoice;Layout.fillWidth:true;model:["Select decision","Accept","Ambiguous","Reject"];enabled:serviceController.status==="draft"&&!serviceController.busy;currentIndex:reviewChoices.count>index?(reviewChoices.get(index).status==="accepted"?1:reviewChoices.get(index).status==="ambiguous"?2:reviewChoices.get(index).status==="rejected"?3:0):0;onActivated:{const status=currentIndex===1?"accepted":currentIndex===2?"ambiguous":currentIndex===3?"rejected":"";reviewChoices.setProperty(index,"status",status);validateReviewChoices()}}TextField{id:decisionNote;Layout.fillWidth:true;placeholderText:"Required review note";visible:true;enabled:serviceController.status==="draft"&&!serviceController.busy;text:reviewChoices.count>index?reviewChoices.get(index).note:"";onTextEdited:{reviewChoices.setProperty(index,"note",text);validateReviewChoices()}}}
          }
        }
      }
      RowLayout{visible:serviceController.parameters.length>0&&serviceController.status==="draft";Layout.fillWidth:true;Label{text:"Reviewer";color:muted}TextField{id:reviewerField;Layout.preferredWidth:240;placeholderText:"Your name";text:"";enabled:!serviceController.busy;onTextChanged:validateReviewChoices()}Label{text:reviewChoicesValid?"Every selected claim has an explicit choice and note":"Every selected claim requires a choice and a nonblank note.";color:reviewChoicesValid?"#70c99a":"#e0ac62";Layout.fillWidth:true;wrapMode:Text.WordWrap}}
      Rectangle{visible:serviceController.publicationIntegrity==="sealed_v2";Layout.fillWidth:true;height:52;color:serviceController.executionReadiness==="ready"?"#203329":"#302b21";border.color:serviceController.executionReadiness==="ready"?"#365f4b":"#725d35";Label{anchors.fill:parent;anchors.margins:8;horizontalAlignment:Text.AlignHCenter;verticalAlignment:Text.AlignVCenter;text:serviceController.executionReadiness==="ready"?"Published and hash-locked; execution readiness is ready.":"Published and hash-locked, but execution readiness is blocked. Resolve the reported gates and missing information before any solver run.";color:serviceController.executionReadiness==="ready"?"#70c99a":"#e0ac62";wrapMode:Text.WordWrap}}
      RowLayout{Layout.fillWidth:true;Item{Layout.fillWidth:true}Button{text:"Close";onClicked:componentDialog.close()}Button{text:"Submit review";visible:serviceController.parameters.length>0&&serviceController.status==="draft";enabled:reviewChoicesValid&&!serviceController.busy;onClicked:serviceController.submitReview(reviewDecisionPayload(),reviewerField.text)}Button{text:"Publish reviewed input";highlighted:true;visible:serviceController.parameters.length>0&&serviceController.status==="reviewed";enabled:!serviceController.busy;onClicked:serviceController.publish()}Button{text:serviceController.status==="exact_package_ready"?"Exact package verified":"Acquire exact package";highlighted:true;visible:serviceController.publicationIntegrity==="sealed_v2";enabled:selectedIndex>=0&&!serviceController.busy&&serviceController.status!=="exact_package_ready";onClicked:serviceController.acquireExactPackage()}}
    }
  }
  Popup{id:moveDialog;anchors.centerIn:Overlay.overlay;width:580;height:570;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:12;Label{text:"TRANSFORM COMPONENT";color:muted;font.bold:true}Label{text:selectedIndex>=0?cadController.parts[selectedIndex].name:"Precise placement";color:window.text;font.pixelSize:22}Label{text:"Canonical translation and extrinsic X→Y→Z rotation propagate to rendering, rotated bounds, measurement, OCCT interference, and joint sweeps.";color:muted;wrapMode:Text.WordWrap;Layout.fillWidth:true}Rectangle{Layout.fillWidth:true;height:1;color:line}
      Label{text:"TRANSLATION (m)";color:muted;font.bold:true;font.pixelSize:10}GridLayout{columns:2;Layout.fillWidth:true;columnSpacing:14;rowSpacing:8;Label{text:"X";color:muted}TextField{id:moveX;validator:DoubleValidator{}}Label{text:"Y";color:muted}TextField{id:moveY;validator:DoubleValidator{}}Label{text:"Z";color:muted}TextField{id:moveZ;validator:DoubleValidator{}}}
      Label{text:"ROTATION (deg)";color:muted;font.bold:true;font.pixelSize:10}GridLayout{columns:2;Layout.fillWidth:true;columnSpacing:14;rowSpacing:8;Label{text:"X";color:muted}TextField{id:rotateX;validator:DoubleValidator{}}Label{text:"Y";color:muted}TextField{id:rotateY;validator:DoubleValidator{}}Label{text:"Z";color:muted}TextField{id:rotateZ;validator:DoubleValidator{}}}
      Label{text:"Rotation is about the imported part-bounds center. Interactive drag gizmos are the next layer.";color:"#e0ac62";wrapMode:Text.WordWrap;Layout.fillWidth:true}Item{Layout.fillHeight:true}RowLayout{Layout.fillWidth:true;Button{text:"Reset";onClicked:{cadController.resetPartTranslation(selectedIndex);moveDialog.close()}}Item{Layout.fillWidth:true}Button{text:"Cancel";onClicked:moveDialog.close()}Button{text:"Apply Transform";highlighted:true;onClicked:{cadController.setPartPlacement(selectedIndex,Number(moveX.text),Number(moveY.text),Number(moveZ.text),Number(rotateX.text),Number(rotateY.text),Number(rotateZ.text));moveDialog.close()}}}
    }}
  Popup{id:measureDialog;anchors.centerIn:Overlay.overlay;width:560;height:460;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:12;Label{text:"MEASURE";color:muted;font.bold:true}Label{text:"Part-to-part measurement";color:window.text;font.pixelSize:22}Rectangle{Layout.fillWidth:true;height:1;color:line}
      Label{text:"First part";color:muted}ComboBox{id:measureA;Layout.fillWidth:true;model:cadController.parts;textRole:"name"}
      Label{text:"Second part";color:muted}ComboBox{id:measureB;Layout.fillWidth:true;model:cadController.parts;textRole:"name";currentIndex:Math.min(1,cadController.parts.length-1)}
      Button{text:"Calculate";enabled:measureA.currentIndex!==measureB.currentIndex;onClicked:measurement=cadController.measureBetween(measureA.currentIndex,measureB.currentIndex)}
      Rectangle{visible:measurement.center_distance_m!==undefined;Layout.fillWidth:true;height:120;color:"#1b2228";border.color:measurement.broad_phase_overlap?"#a57a35":"#365f4b";Column{anchors.fill:parent;anchors.margins:12;spacing:5;Label{text:"Center distance  "+Number(measurement.center_distance_m||0).toFixed(5)+" m";color:window.text;font.bold:true}Label{text:"ΔX "+Number(measurement.dx_m||0).toFixed(5)+"   ΔY "+Number(measurement.dy_m||0).toFixed(5)+"   ΔZ "+Number(measurement.dz_m||0).toFixed(5)+" m";color:muted}Label{text:"AABB clearance  "+Number(measurement.aabb_clearance_m||0).toFixed(5)+" m";color:muted}Label{text:measurement.broad_phase_overlap?"Bounding boxes overlap — consult confirmed interference results.":"Bounding boxes are separated.";color:measurement.broad_phase_overlap?"#e0ac62":"#70c99a"}}}
      Item{Layout.fillHeight:true}RowLayout{Layout.fillWidth:true;Item{Layout.fillWidth:true}Button{text:"Close";onClicked:measureDialog.close()}}
    }}
  Popup{id:mateDialog;anchors.centerIn:Overlay.overlay;width:620;height:620;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:11;Label{text:"SNAP MATE";color:muted;font.bold:true}Label{text:"Align deterministic geometry anchors";color:window.text;font.pixelSize:22}Label{text:"Translate one part so its selected anchor coincides with the target anchor. Orientation is preserved.";color:muted;wrapMode:Text.WordWrap;Layout.fillWidth:true}Rectangle{Layout.fillWidth:true;Layout.preferredHeight:1;color:line}
      Label{text:"Moving part";color:muted}ComboBox{id:mateMoving;Layout.fillWidth:true;model:cadController.parts;textRole:"name";currentIndex:Math.min(2,cadController.parts.length-1)}
      Label{text:"Moving anchor";color:muted}ComboBox{id:mateMovingAnchor;Layout.fillWidth:true;model:cadController.placementAnchors(mateMoving.currentIndex);textRole:"label"}
      Label{text:"Target part";color:muted}ComboBox{id:mateTarget;Layout.fillWidth:true;model:cadController.parts;textRole:"name";currentIndex:0}
      Label{text:"Target anchor";color:muted}ComboBox{id:mateTargetAnchor;Layout.fillWidth:true;model:cadController.placementAnchors(mateTarget.currentIndex);textRole:"label"}
      Label{text:"Connection semantics (user-confirmed)";color:muted}ComboBox{id:mateConnectionType;Layout.fillWidth:true;model:["Fixed","Revolute","Sliding","Contact"]}
      Rectangle{Layout.fillWidth:true;Layout.preferredHeight:62;color:"#302b21";border.color:"#725d35";Label{anchors.fill:parent;anchors.margins:9;text:"These are bounds-derived placement anchors, not confirmed mounting interfaces. Prometheus will not infer a fastener, joint, fit, or load path from this operation.";color:"#d7c39d";wrapMode:Text.WordWrap}}
      Item{Layout.fillHeight:true}RowLayout{Layout.fillWidth:true;Item{Layout.fillWidth:true}Button{text:"Cancel";onClicked:mateDialog.close()}Button{text:"Snap Only";enabled:mateMoving.currentIndex!==mateTarget.currentIndex&&mateMovingAnchor.currentIndex>=0&&mateTargetAnchor.currentIndex>=0;onClicked:{const moving=mateMovingAnchor.model[mateMovingAnchor.currentIndex],target=mateTargetAnchor.model[mateTargetAnchor.currentIndex];if(cadController.snapPlacementAnchors(mateMoving.currentIndex,moving.id,mateTarget.currentIndex,target.id))mateDialog.close()}}Button{text:"Snap + Confirm";highlighted:true;enabled:mateMoving.currentIndex!==mateTarget.currentIndex&&mateMovingAnchor.currentIndex>=0&&mateTargetAnchor.currentIndex>=0;onClicked:{const moving=mateMovingAnchor.model[mateMovingAnchor.currentIndex],target=mateTargetAnchor.model[mateTargetAnchor.currentIndex],type=mateConnectionType.currentText.toLowerCase();if(cadController.confirmAnchorConnection(mateMoving.currentIndex,moving.id,mateTarget.currentIndex,target.id,type))mateDialog.close()}}}
    }}
  Popup{id:connectionDialog;anchors.centerIn:Overlay.overlay;width:680;height:480;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:12;Label{text:"CONNECTION SEMANTICS";color:muted;font.bold:true}Label{text:"Classify confirmed solid engagement";color:window.text;font.pixelSize:22}Label{text:"Geometry establishes overlap; you establish whether the overlap is intended.";color:muted;wrapMode:Text.WordWrap;Layout.fillWidth:true}Rectangle{Layout.fillWidth:true;height:1;color:line}
      ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:cadController.interferences;spacing:8;delegate:Rectangle{width:ListView.view.width;height:120;color:"#1b2228";border.color:modelData.classification==="prohibited"?"#b85450":modelData.classification==="intended_engagement"?"#365f4b":"#a57a35";RowLayout{anchors.fill:parent;anchors.margins:12;ColumnLayout{Layout.fillWidth:true;Label{text:modelData.first_name+"  ↔  "+modelData.second_name;color:window.text;font.bold:true}Label{text:Number(modelData.volume_m3).toExponential(3)+" m³ confirmed by OCCT Boolean common-volume";color:muted}Label{text:"Current: "+String(modelData.classification).replace(/_/g," ");color:modelData.classification==="prohibited"?"#e87972":modelData.classification==="intended_engagement"?"#70c99a":"#e0ac62"}}ColumnLayout{Label{text:"Classification";color:muted}ComboBox{id:classChoice;model:["Unclassified","Intended engagement","Prohibited interference"];currentIndex:modelData.classification==="intended_engagement"?1:modelData.classification==="prohibited"?2:0;onActivated:{const value=currentIndex===1?"intended_engagement":currentIndex===2?"prohibited":"unclassified";cadController.classifyInterference(modelData.first_id,modelData.second_id,value)}}}}}}
      RowLayout{Layout.fillWidth:true;Label{text:"Classification is project-specific and retained in the project manifest.";color:muted}Item{Layout.fillWidth:true}Button{text:"Done";onClicked:connectionDialog.close()}}
    }}
  Popup{id:semanticConnectionsDialog;anchors.centerIn:Overlay.overlay;width:760;height:520;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:10;Label{text:"SEMANTIC CONNECTIONS";color:muted;font.bold:true}Label{text:"User-confirmed assembly graph edges";color:window.text;font.pixelSize:22}Label{text:"Provisional geometry-anchor connections are stored separately from collision results and component-package interface evidence.";color:muted;wrapMode:Text.WordWrap;Layout.fillWidth:true}Rectangle{Layout.fillWidth:true;Layout.preferredHeight:1;color:line}
      ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:cadController.connections;spacing:7;delegate:Rectangle{width:ListView.view.width;height:92;color:"#1b2228";border.color:"#365f4b";RowLayout{anchors.fill:parent;anchors.margins:11;ColumnLayout{Layout.fillWidth:true;Label{text:modelData.source_name+"  →  "+modelData.target_name;color:window.text;font.bold:true}Label{text:modelData.connection_type.toUpperCase()+"  •  "+modelData.source_anchor+" → "+modelData.target_anchor;color:"#70c99a"}Label{text:"Basis: user confirmed • bounds-derived anchors • provisional";color:"#d8b36e";font.pixelSize:10}}Button{text:"Remove";onClicked:cadController.removeConnection(index)}}}}
      RowLayout{Layout.fillWidth:true;Label{text:"Removing an edge does not move either part.";color:muted}Item{Layout.fillWidth:true}Button{text:"Done";onClicked:semanticConnectionsDialog.close()}}
    }}
  Popup{id:jointDialog;anchors.centerIn:Overlay.overlay;width:520;height:430;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:12;Label{text:"DEFINE REVOLUTE JOINT";color:muted;font.bold:true}Label{text:"Confirm the semantic connection";color:window.text;font.pixelSize:22}Rectangle{Layout.fillWidth:true;height:1;color:line}
      Label{text:"Driven component";color:muted}ComboBox{id:jointSource;Layout.fillWidth:true;model:cadController.parts;textRole:"name";currentIndex:Math.min(1,cadController.parts.length-1)}
      Label{text:"Rotating component";color:muted}ComboBox{id:jointTarget;Layout.fillWidth:true;model:cadController.parts;textRole:"name";currentIndex:Math.min(2,cadController.parts.length-1)}
      RowLayout{Layout.fillWidth:true;ColumnLayout{Label{text:"Axis";color:muted}ComboBox{id:jointAxis;model:["X","Y","Z"];currentIndex:2}}ColumnLayout{Layout.fillWidth:true;Label{text:"Minimum (deg)";color:muted}TextField{id:jointMin;text:"0";validator:DoubleValidator{}}}ColumnLayout{Layout.fillWidth:true;Label{text:"Maximum (deg)";color:muted}TextField{id:jointMax;text:"90";validator:DoubleValidator{}}}}
      Label{text:"The source-part center is used as the joint pivot. Axis, pivot, and limits are user-confirmed because neutral STEP does not preserve mates.";color:"#e0ac62";wrapMode:Text.WordWrap;Layout.fillWidth:true}Item{Layout.fillHeight:true}RowLayout{Layout.fillWidth:true;Item{Layout.fillWidth:true}Button{text:"Cancel";onClicked:jointDialog.close()}Button{text:"Confirm Joint";highlighted:true;onClicked:{const p=cadController.parts[jointSource.currentIndex];engineeringController.defineRevoluteJoint(jointSource.currentIndex,jointTarget.currentIndex,jointAxis.currentText,Number(jointMin.text),Number(jointMax.text),p.centerX,p.centerY,p.centerZ);jointDialog.close()}}}
    }}
  Popup{id:scenarioDialog;anchors.centerIn:Overlay.overlay;width:650;height:580;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:22;spacing:10;Label{text:"DEFINE TEST";color:muted;font.bold:true}Label{text:"Rotate motor-driven arm";color:window.text;font.pixelSize:22}Label{text:"Review the structured interpretation before accepting it.";color:muted}Rectangle{Layout.fillWidth:true;height:1;color:line}
      Rectangle{Layout.fillWidth:true;Layout.preferredHeight:62;color:"#302b21";border.color:"#725d35";Label{anchors.fill:parent;anchors.margins:9;text:"Conformance demo: the current C++ motor-arm checks still use fixed fixture inputs and do not yet consume this published package.";color:"#d7c39d";wrapMode:Text.WordWrap}}
      GridLayout{columns:2;columnSpacing:15;rowSpacing:9;Layout.fillWidth:true
        Label{text:"Payload (kg)";color:muted}TextField{id:payload;text:"8.0";validator:DoubleValidator{bottom:0}}
        Label{text:"Arm radius (m)";color:muted}TextField{id:armLength;text:"0.20";validator:DoubleValidator{bottom:0}}
        Label{text:"Rotation (deg)";color:muted}TextField{id:rotation;text:"90";validator:DoubleValidator{bottom:0}}
        Label{text:"Movement duration (s)";color:muted}TextField{id:moveTime;text:"1.2";validator:DoubleValidator{bottom:0}}
        Label{text:"Horizontal hold (s)";color:muted}TextField{id:holdTime;text:"4.0";validator:DoubleValidator{bottom:0}}
        Label{text:"Cycle period (s)";color:muted}TextField{id:cycleTime;text:"10.0";validator:DoubleValidator{bottom:0}}
        Label{text:"Ambient temperature (°C)";color:muted}TextField{id:ambient;text:"35";validator:DoubleValidator{}}
      }
      Rectangle{Layout.fillWidth:true;height:58;color:"#302b21";border.color:"#725d35";Label{anchors.fill:parent;anchors.margins:9;text:"Assumption requiring review: symmetric triangular velocity profile; gearbox efficiency nominal 0.70, bounded 0.55–0.82. Exact efficiency is missing.";color:"#d7c39d";wrapMode:Text.WordWrap}}
      Item{Layout.fillHeight:true}RowLayout{Layout.fillWidth:true;Item{Layout.fillWidth:true}Button{text:"Cancel";onClicked:scenarioDialog.close()}Button{text:"Confirm Scenario";highlighted:true;onClicked:{engineeringController.defineMotorArmScenario(Number(payload.text),Number(armLength.text),Number(rotation.text),Number(moveTime.text),Number(holdTime.text),Number(cycleTime.text),Number(ambient.text));scenarioDialog.close()}}}
    }}
  Popup{id:resultsDialog;anchors.centerIn:Overlay.overlay;width:900;height:700;modal:true;focus:true;background:Rectangle{color:"#222a31";border.color:"#53616c"}
    ColumnLayout{anchors.fill:parent;anchors.margins:20;spacing:10;RowLayout{Layout.fillWidth:true;Column{Label{text:"TEST BUILD RESULTS";color:muted;font.bold:true}Label{text:engineeringController.runStatus;color:window.text;font.pixelSize:23}}Item{Layout.fillWidth:true}Button{text:"×";flat:true;onClicked:resultsDialog.close()}}Rectangle{Layout.fillWidth:true;height:1;color:line}
      Label{text:"CHEAPEST SUFFICIENT METHODS  •  algebraic drivetrain  •  current estimate  •  one-node thermal RC";color:muted;font.pixelSize:11}
      ListView{Layout.fillWidth:true;Layout.fillHeight:true;clip:true;model:engineeringController.findings;spacing:7;delegate:Rectangle{width:ListView.view.width;height:modelData.estimated_range!==""?118:104;color:"#1b2228";border.color:modelData.status==="fail"?"#b85450":modelData.status==="caution"?"#a57a35":"#365f4b"
        RowLayout{anchors.fill:parent;anchors.margins:11;spacing:12;Rectangle{width:8;Layout.fillHeight:true;color:modelData.status==="fail"?"#d96862":modelData.status==="caution"?"#d1a650":"#67bf91"}ColumnLayout{Layout.fillWidth:true;spacing:3;RowLayout{Layout.fillWidth:true;Label{text:modelData.status.toUpperCase();color:modelData.status==="fail"?"#e87972":modelData.status==="caution"?"#e0b861":"#70c99a";font.bold:true}Label{text:modelData.title;color:window.text;font.bold:true;font.pixelSize:15}Item{Layout.fillWidth:true}Label{text:(modelData.unit==="m³"?Number(modelData.calculated).toExponential(3):Number(modelData.calculated).toFixed(3))+" "+modelData.unit+((modelData.available||0)!==0?"  /  limit "+Number(modelData.available).toFixed(3):"");color:window.text}}
          Label{text:modelData.mechanism;color:muted;Layout.fillWidth:true;wrapMode:Text.WordWrap}Label{visible:modelData.estimated_range!=="";text:"Estimated range: "+modelData.estimated_range;color:"#d8b36e";font.pixelSize:10;elide:Text.ElideRight;Layout.fillWidth:true}Label{text:"Evidence: "+modelData.evidence;color:"#83b6d5";font.pixelSize:10;elide:Text.ElideRight;Layout.fillWidth:true}Label{visible:modelData.assumption!=="";text:"Assumption: "+modelData.assumption;color:"#d8b36e";font.pixelSize:10;elide:Text.ElideRight;Layout.fillWidth:true}}
        }} }
      RowLayout{Layout.fillWidth:true;Label{text:"No certification claim. Unknown assembly masses prevent a complete COG pass.";color:muted}Item{Layout.fillWidth:true}Button{text:"Close";onClicked:resultsDialog.close()}}
    }}
}
