#include "service_controller.hpp"
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkReply>
#include <QUuid>

ServiceController::ServiceController(QObject* parent):QObject(parent){checkHealth();}
QNetworkRequest ServiceController::request(const QString& path)const{QNetworkRequest value(QUrl("http://127.0.0.1:8000"+path));value.setHeader(QNetworkRequest::ContentTypeHeader,"application/json");return value;}
void ServiceController::setBusy(bool value){if(busy_==value)return;busy_=value;emit busyChanged();}
void ServiceController::fail(const QString& message){error_=message;status_="error";setBusy(false);emit changed();}
void ServiceController::reset(){status_.clear();error_.clear();job_id_.clear();candidate_.clear();parameters_.clear();events_.clear();emit changed();}
void ServiceController::checkHealth(){auto* reply=network_.get(request("/v1/health"));connect(reply,&QNetworkReply::finished,this,[this,reply]{const bool value=reply->error()==QNetworkReply::NoError;if(online_!=value){online_=value;emit onlineChanged();}reply->deleteLater();});}
void ServiceController::research(const QString& manufacturer,const QString& part_number){reset();setBusy(true);status_="researching";emit changed();QJsonObject body{{"manufacturer",manufacturer},{"part_number",part_number}};auto req=request("/v1/research-jobs");req.setRawHeader("Idempotency-Key",QUuid::createUuid().toString(QUuid::WithoutBraces).toUtf8());auto* reply=network_.post(req,QJsonDocument(body).toJson(QJsonDocument::Compact));connect(reply,&QNetworkReply::finished,this,[this,reply]{if(reply->error()!=QNetworkReply::NoError){fail("Research service unavailable: "+reply->errorString());reply->deleteLater();return;}consumeJob(reply->readAll());reply->deleteLater();});}
void ServiceController::consumeJob(const QByteArray& data){const auto object=QJsonDocument::fromJson(data).object();job_id_=object.value("id").toString();status_=object.value("status").toString();candidate_=object.value("candidate").toObject().toVariantMap();parameters_=object.value("candidate").toObject().value("parameters").toArray().toVariantList();events_=object.value("events").toArray().toVariantList();setBusy(false);emit changed();}
void ServiceController::acceptAndPublish(const QString& reviewer){if(job_id_.isEmpty())return;setBusy(true);QJsonArray decisions;for(const auto& value:parameters_)decisions.append(QJsonObject{{"field_name",value.toMap().value("field_name").toString()},{"status","accepted"}});QJsonObject body{{"reviewed_by",reviewer},{"decisions",decisions}};auto* reply=network_.post(request("/v1/research-jobs/"+job_id_+"/review"),QJsonDocument(body).toJson(QJsonDocument::Compact));connect(reply,&QNetworkReply::finished,this,[this,reply]{if(reply->error()!=QNetworkReply::NoError){fail("Evidence review failed: "+reply->errorString());reply->deleteLater();return;}reply->deleteLater();auto req=request("/v1/research-jobs/"+job_id_+"/publish");req.setRawHeader("Idempotency-Key",QUuid::createUuid().toString(QUuid::WithoutBraces).toUtf8());auto* publish_reply=network_.post(req,QByteArray("{}"));connect(publish_reply,&QNetworkReply::finished,this,[this,publish_reply]{if(publish_reply->error()!=QNetworkReply::NoError){fail("Publishing failed: "+publish_reply->errorString());publish_reply->deleteLater();return;}const auto object=QJsonDocument::fromJson(publish_reply->readAll()).object();candidate_=object.toVariantMap();parameters_=object.value("parameters").toArray().toVariantList();status_="published";setBusy(false);emit changed();emit published(candidate_);publish_reply->deleteLater();});});}
