"""initial normalized schema

Revision ID: cd418805b2c6
Revises: 
Create Date: 2026-08-10 16:57:38.100313
"""
from typing import Sequence,Union
from alembic import op
import sqlalchemy as sa

revision: str = 'cd418805b2c6'
down_revision: Union[str,None] = None
branch_labels: Union[str,Sequence[str],None] = None
depends_on: Union[str,Sequence[str],None] = None
def upgrade()->None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_packages',
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('model_level', sa.String(), nullable=False),
    sa.Column('model_class', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.String(), nullable=False),
    sa.Column('result_reference', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_manufacturers_normalized_name'), 'manufacturers', ['normalized_name'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit_system', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_hash', sa.String(), nullable=False),
    sa.Column('rights_status', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_hash')
    )
    op.create_table('assemblies',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('source_format', sa.String(), nullable=False),
    sa.Column('geometry_hash', sa.String(), nullable=False),
    sa.Column('hierarchy', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('components',
    sa.Column('manufacturer_id', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('normalized_part_number', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('model_class', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_id', 'part_number', name='uq_component_mfr_part')
    )
    op.create_index(op.f('ix_components_normalized_part_number'), 'components', ['normalized_part_number'], unique=False)
    op.create_table('connections',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('source_part', sa.String(), nullable=False),
    sa.Column('target_part', sa.String(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('confirmed_by_user', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_claims',
    sa.Column('component_package_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=False),
    sa.Column('normalized_value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=False),
    sa.Column('page_or_figure', sa.String(), nullable=False),
    sa.Column('source_authority', sa.String(), nullable=False),
    sa.Column('extraction_status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['component_package_id'], ['component_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('natural_language_description', sa.Text(), nullable=False),
    sa.Column('structured_definition', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_runs',
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('planned_checks', sa.Text(), nullable=False),
    sa.Column('omitted_checks', sa.Text(), nullable=False),
    sa.Column('manifest', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_revisions',
    sa.Column('component_id', sa.String(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('parent_revision_id', sa.String(), nullable=True),
    sa.Column('certification_tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['component_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_id', 'revision', name='uq_component_revision')
    )
    op.create_table('component_parameters',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('value_si', sa.String(), nullable=False),
    sa.Column('unit_si', sa.String(), nullable=False),
    sa.Column('original_value', sa.String(), nullable=False),
    sa.Column('original_unit', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['component_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'field_name', name='uq_revision_parameter')
    )
    op.create_table('findings',
    sa.Column('check_run_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('failure_mechanism', sa.String(), nullable=False),
    sa.Column('affected_entities', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_component_bindings',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('cad_entity_id', sa.String(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['component_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cad_entity_id', name='uq_project_cad_binding')
    )
    op.create_table('research_jobs',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['component_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('evidence_records',
    sa.Column('parameter_id', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=False),
    sa.Column('source_locator', sa.String(), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('evidence_class', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['component_parameters.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_job_events',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('sequence', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade()->None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_job_events')
    op.drop_table('evidence_records')
    op.drop_table('research_jobs')
    op.drop_table('project_component_bindings')
    op.drop_table('findings')
    op.drop_table('component_parameters')
    op.drop_table('component_revisions')
    op.drop_table('check_runs')
    op.drop_table('scenarios')
    op.drop_table('evidence_claims')
    op.drop_table('connections')
    op.drop_index(op.f('ix_components_normalized_part_number'), table_name='components')
    op.drop_table('components')
    op.drop_table('assemblies')
    op.drop_table('source_documents')
    op.drop_table('projects')
    op.drop_index(op.f('ix_manufacturers_normalized_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_table('jobs')
    op.drop_table('component_packages')
    # ### end Alembic commands ###
